export const LOAD_EVENTS_START = "LOAD_EVENTS_START";
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const LOAD_EVENTS_ERROR = "LOAD_EVENTS_ERROR";
export const LOAD_RESOURCES_START = "LOAD_RESOURCES_START";
export const LOAD_RESOURCES_SUCCESS = "LOAD_RESOURCES_SUCCESS";
export const LOAD_RESOURCES_ERROR = "LOAD_RESOURCES_ERROR";
export const RESET_ALL_DATA = "RESET_ALL_DATA";
